import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import Section from "./components/ui/pagelayout/Section";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-primary">
        <Theme>
          <Section className="bg-primary drop-shadow-lg">
            <Container className=" w-[1120px] mx-auto">
              <Navbar />
            </Container>
          </Section>
          <Container className=" w-[1120px] mx-auto">{children}</Container>
          <Section className="bg-primary">
            <Footer />
          </Section>
        </Theme>
      </body>
    </html>
  );
}
